### ISSUE TITLE
Using self instead of that

### ISSUE THREAD

**Issue by chrisranderson** [BonsaiDen/JavaScript-Garden#269] opened 2015-02-07 15:53 UTC
Foo.method = function() {
    var that = this;
    function test() {
        // Use that instead of this here
    }
    test();
}

The word "that" is the opposite of "this" - when referring to itself, "self" seems to be clearer. Seems like "that" would refer to some other object. For example, if I was working on a car, if I said "this" car you would know I was talking about the one I was working on, but if I said that car it would be some other car that I was not working on.

**Comment by timruffles** [comment] 2015-02-07 17:59
Agreed, PR will be accepted.

**Comment by fediev** [comment] 2015-02-17 12:47
"self" has more explicit meaning than "that" and is used in other languages such as python. But use of "that" is a common convention in javascript, that was introduced in 'JavaScript The Good Part'. 

I think that use of "that" has some good reasons and is a convention, so it's not good to use "self" instead of "that".

**Comment by peterjwest** [comment] 2015-03-04 13:42
I think the issue is that 'this' and 'that' are used to refer to two *different* things in English language. While 'this' and 'self' have roughly the same intent in an OO context.

It's not really a big deal though, once you understand the concept, it's just a word. We could clarify the convention of using `self` and `that` when we first use it in Javascript Garden.

**Comment by fediev** [comment] 2015-03-10 20:06
I agree that it's not a big deal and it's just a convention. 

`this` and `self` are roughly the same meaning as you mentioned. But IMHO, `that` has more meaning than `self`. `that` is naturally understood as the alternative of `this` and reminds "in this scope, `this` is not the same `this` of outer scope, so another variable name is used here instead of `this`." 

So I prefer `that` to `self`. But again, I agree that it's just a convention.

**Comment by marijaninjo** [comment] 2015-03-25 16:24
@peterjwest please listen to @fediev this and that definitely make much more sense in context of scopes

**Comment by timruffles** [comment] 2015-03-25 16:32
I think `self` is more [widely](https://github.com/search?utf8=%E2%9C%93&q=%22var+self%22&type=Code&ref=searchresults) [adopted](https://github.com/search?l=javascript&q=%22var+that%22&ref=searchresults&type=Code&utf8=%E2%9C%93) in JS.

**Comment by peterjwest** [comment] 2015-03-25 21:16
I'm going to close this issue. We've already previously accepted a PR to standardise on `self` rather than `that`, there are arguments for both sides, and it's not a big issue so we're going to stick with `self`.

**Closed by peterjwest** 2015-03-25 21:16 UTC

**Comment by lewisje** [comment] 2016-05-29 19:01
An argument that wasn't made previously here is that in browsers, `self` is already an alias for `window`; then again, it is very rare to use it for this purpose, and in the pattern you're using it in, the global `self` is merely shadowed rather than overwritten.

**Comment by peterjwest** [comment] 2016-05-29 20:23
Interesting, good to know!
